- name: Ensure iptables-persistent is installed
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  become: true

- name: Open TCP port {{ couding_open_port }} using iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ couding_open_port }}"
    jump: ACCEPT
    state: absent
    ip_version: ipv4
    comment: "Allow TCP port {{ couding_open_port }}"
  become: true

- name: Save iptables rules (IPv4) to persist across reboots
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    ip_version: ipv4
    state: saved
  become: true
