version: "3.9"

services:
  app:
    image: vipuldockerhub/clouding-backend:${SERVER_VERSION}
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env:ro
    restart: always
