---
galaxy_info:
  author: Vipul
  description: Simple role to install Docker Engine, CLI, Compose, and start the service
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []