---
- name: Ensure ufw package is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

- name: Ensure UFW service is enabled and started
  ansible.builtin.systemd:
    name: ufw
    enabled: yes
    state: started

- name: Allow SSH to prevent lockout
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow custom port via UFW
  community.general.ufw:
    rule: allow
    port: "{{ port_value }}"
    proto: tcp
  become: true

- name: Enable UFW safely
  community.general.ufw:
    state: enabled

- name: Show UFW status
  ansible.builtin.command: ufw status verbose
  register: ufw_status
