version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.15.4
    container_name: vault
    user: "0"
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/vault/data:/vault/data:rw
      - ./config.hcl:/vault/config/config.hcl:ro
    entrypoint: ["vault"]
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    command: server -config=/vault/config/config.hcl