---
galaxy_info:
  author: Vipul
  description: Install OpenJDK (version via var, default 8). Debian & RHEL families.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: EL
      versions: [all]
dependencies: []