---
- hosts: localhost
  gather_facts: yes
  vars:
    PORT: 8080
  roles:
    - role: clouding.OpenPort
  tasks:
    - debug:
        msg: "Hello from Ansible"
    - name: Wait for 1 seconds
      ansible.builtin.pause:
        seconds: 1
    - name: Wait for 2 seconds
      ansible.builtin.pause:
        seconds: 2
