---
galaxy_info:
  author: Vipul
  description: Clone a public GitHub repo and run its root Docker Compose.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: EL
      versions: [all]
dependencies: []