name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'       # only trigger when backend changes
      - '.github/workflows/docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: version
        run: |
          VERSION=$(cat backend/VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: vipuldockerhub/clouding-backend:${{ steps.version.outputs.version }}
