---
# tasks/main.yml
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install NGINX
  become: yes
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure NGINX is running and enabled
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  when: not ansible_check_mode