---
galaxy_info:
  author: Vipul
  description: Drop an NGINX site file into sites-available and symlink it into sites-enabled.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
dependencies: []